### ISSUE TITLE
Can't scan barcodes but qr codes working fine 

### ISSUE THREAD

**Issue by brendan1809** [mkdesilva/react-native-qr-image-reader#3]

**Comment by mkdesilva** [comment]
This has been fixed in the latest version, I will close this issue.

**Comment by mkdesilva** [comment]
Fixed in [v1.0.3](https://github.com/mkdesilva/react-native-qr-image-reader/releases/tag/v1.0.3)

**Comment by mkdesilva** [comment]
@brendan1809 Could you please provide some more details? 

Please share the barcode you’re trying to scan as well if possible.

**Comment by brendan1809** [comment]
I used my android device to to upload this image and i get `decode_error`
![Screenshot_2021-02-21-18-26-57-77](https://user-images.githubusercontent.com/55783210/108622262-82885a80-7472-11eb-8206-6853006f71a5.jpg)

**Comment by brendan1809** [comment]
I tried downloading the barcode from google and it can read the barcodes
![440px-UPC-A-036000291452 svg](https://user-images.githubusercontent.com/55783210/108677376-8bd1ff80-7524-11eb-84b4-b889a7423c11.png)

**Comment by mkdesilva** [comment]
@brendan1809 
So, I found out this is happening because of the image resizing this library does.

I have updated the logic so it will scan the original image first before resizing.
If it does not find any codes, it will resize it and scan it again. 

This was implemented in #4 and released in [v1.0.4](https://github.com/mkdesilva/react-native-qr-image-reader/releases/tag/v1.0.4)
